#!/bin/bash
#==============================================================================
# Setup Environment Script
#==============================================================================
# Extracts Terraform outputs and generates .env files for backend and frontend
#
# Usage:
#   ./scripts/setup-env.sh [stage]
#
# Examples:
#   ./scripts/setup-env.sh dev
#   ./scripts/setup-env.sh staging
#   ./scripts/setup-env.sh prod
#==============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
STAGE="${1:-dev}"
INFRA_DIR="infrastructure/environments/${STAGE}"
BACKEND_ENV_FILE=".env.${STAGE}"
FRONTEND_ENV_FILE="packages/web/.env.${STAGE}"

echo -e "${BLUE}==> Setting up environment for stage: ${STAGE}${NC}"

#==============================================================================
# Check prerequisites
#==============================================================================
check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"

    # Check if jq is installed
    if ! command -v jq &> /dev/null; then
        echo -e "${RED}Error: jq is required but not installed.${NC}"
        echo "Install with: brew install jq (macOS) or apt-get install jq (Linux)"
        exit 1
    fi

    # Check if terraform is installed
    if ! command -v terraform &> /dev/null; then
        echo -e "${RED}Error: terraform is required but not installed.${NC}"
        exit 1
    fi

    # Check if infrastructure directory exists
    if [ ! -d "$INFRA_DIR" ]; then
        echo -e "${RED}Error: Infrastructure directory not found: ${INFRA_DIR}${NC}"
        echo "Available stages:"
        ls -1 infrastructure/environments/ 2>/dev/null || echo "  (none found)"
        exit 1
    fi

    echo -e "${GREEN}Prerequisites OK${NC}"
}

#==============================================================================
# Get Terraform outputs
#==============================================================================
get_terraform_outputs() {
    echo -e "${YELLOW}Fetching Terraform outputs...${NC}"

    cd "$INFRA_DIR"

    # Check if terraform has been initialized
    if [ ! -d ".terraform" ]; then
        echo -e "${YELLOW}Terraform not initialized. Running init...${NC}"
        terraform init -input=false
    fi

    # Get outputs as JSON
    TERRAFORM_OUTPUT=$(terraform output -json 2>/dev/null)

    if [ -z "$TERRAFORM_OUTPUT" ] || [ "$TERRAFORM_OUTPUT" == "{}" ]; then
        echo -e "${RED}Error: No Terraform outputs found.${NC}"
        echo "Make sure you have run 'terraform apply' first."
        exit 1
    fi

    cd - > /dev/null

    echo -e "${GREEN}Terraform outputs fetched successfully${NC}"
}

#==============================================================================
# Extract values from Terraform outputs
#==============================================================================
extract_value() {
    local key=$1
    echo "$TERRAFORM_OUTPUT" | jq -r ".${key}.value // empty"
}

#==============================================================================
# Generate backend .env file
#==============================================================================
generate_backend_env() {
    echo -e "${YELLOW}Generating backend environment file: ${BACKEND_ENV_FILE}${NC}"

    # Extract values
    AWS_REGION=$(extract_value "aws_region")
    ENVIRONMENT=$(extract_value "environment")
    DYNAMODB_TABLE=$(extract_value "dynamodb_table_name")
    S3_BUCKET_DOCUMENTS=$(extract_value "s3_bucket_documents_name")
    SQS_QUEUE_URL=$(extract_value "sqs_queue_url")
    SQS_QUEUE_ARN=$(extract_value "sqs_queue_arn")
    EVENT_BUS_NAME=$(extract_value "event_bus_name")
    COGNITO_USER_POOL_ID=$(extract_value "user_pool_id")
    COGNITO_APP_CLIENT_ID=$(extract_value "app_client_id")
    COGNITO_USER_POOL_ARN=$(extract_value "user_pool_arn")

    # Generate a webhook secret if not exists
    WEBHOOK_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "change-me-in-production")

    cat > "$BACKEND_ENV_FILE" << EOF
#==============================================================================
# Mortgage Platform Backend - Environment Configuration
# Generated by setup-env.sh on $(date)
# Stage: ${STAGE}
#==============================================================================

# AWS Configuration
AWS_REGION=${AWS_REGION:-us-east-1}
ENVIRONMENT=${ENVIRONMENT:-${STAGE}}

# DynamoDB
DYNAMODB_TABLE=${DYNAMODB_TABLE}

# S3
S3_BUCKET_DOCUMENTS=${S3_BUCKET_DOCUMENTS}

# SQS
SQS_QUEUE_URL=${SQS_QUEUE_URL}
SQS_QUEUE_ARN=${SQS_QUEUE_ARN}

# EventBridge
EVENT_BUS_NAME=${EVENT_BUS_NAME}

# Cognito
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
COGNITO_USER_POOL_ARN=${COGNITO_USER_POOL_ARN}

# Webhooks
WEBHOOK_SECRET=${WEBHOOK_SECRET}

# Debug (set to true for verbose logging)
DEBUG=false
EOF

    echo -e "${GREEN}Backend .env file created: ${BACKEND_ENV_FILE}${NC}"
}

#==============================================================================
# Generate frontend .env file
#==============================================================================
generate_frontend_env() {
    echo -e "${YELLOW}Generating frontend environment file: ${FRONTEND_ENV_FILE}${NC}"

    # Extract values
    AWS_REGION=$(extract_value "aws_region")
    COGNITO_USER_POOL_ID=$(extract_value "user_pool_id")
    COGNITO_APP_CLIENT_ID=$(extract_value "app_client_id")
    COGNITO_USER_POOL_ENDPOINT=$(extract_value "user_pool_endpoint")

    # API URL will be set after serverless deploy
    # For now, we use a placeholder or try to get it from serverless info
    API_URL=""
    if command -v sls &> /dev/null; then
        API_URL=$(cd .. && pnpm sls info --stage ${STAGE} 2>/dev/null | grep -o 'https://[^[:space:]]*' | head -1 || echo "")
    fi

    cat > "$FRONTEND_ENV_FILE" << EOF
#==============================================================================
# Mortgage Platform Frontend - Environment Configuration
# Generated by setup-env.sh on $(date)
# Stage: ${STAGE}
#==============================================================================

# API Configuration
# NOTE: Update this after running 'make backend-deploy'
VITE_API_URL=${API_URL:-https://your-api-gateway-url.execute-api.${AWS_REGION:-us-east-1}.amazonaws.com/${STAGE}}

# AWS Region
VITE_AWS_REGION=${AWS_REGION:-us-east-1}

# Cognito Configuration
VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
VITE_COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
VITE_COGNITO_REGION=${AWS_REGION:-us-east-1}

# Optional: OAuth configuration (if using hosted UI)
# VITE_COGNITO_OAUTH_DOMAIN=your-domain.auth.${AWS_REGION:-us-east-1}.amazoncognito.com
# VITE_COGNITO_OAUTH_REDIRECT_SIGNIN=http://localhost:5173/callback
# VITE_COGNITO_OAUTH_REDIRECT_SIGNOUT=http://localhost:5173/

# Environment
VITE_ENVIRONMENT=${STAGE}
EOF

    echo -e "${GREEN}Frontend .env file created: ${FRONTEND_ENV_FILE}${NC}"
}

#==============================================================================
# Update SSM Parameters (optional, for Serverless Framework)
#==============================================================================
update_ssm_parameters() {
    echo -e "${YELLOW}Updating SSM parameters...${NC}"

    local SSM_PREFIX="/mortgage-platform/${STAGE}"

    # Check if aws cli is available
    if ! command -v aws &> /dev/null; then
        echo -e "${YELLOW}AWS CLI not found. Skipping SSM parameter updates.${NC}"
        return
    fi

    # Update SSM parameters from Terraform outputs
    declare -A params=(
        ["dynamodb_table_name"]=$(extract_value "dynamodb_table_name")
        ["s3_bucket_documents_name"]=$(extract_value "s3_bucket_documents_name")
        ["sqs_queue_url"]=$(extract_value "sqs_queue_url")
        ["sqs_queue_arn"]=$(extract_value "sqs_queue_arn")
        ["event_bus_name"]=$(extract_value "event_bus_name")
        ["user_pool_id"]=$(extract_value "user_pool_id")
        ["app_client_id"]=$(extract_value "app_client_id")
        ["user_pool_arn"]=$(extract_value "user_pool_arn")
    )

    for key in "${!params[@]}"; do
        local value="${params[$key]}"
        if [ -n "$value" ]; then
            echo "  Setting ${SSM_PREFIX}/${key}..."
            aws ssm put-parameter \
                --name "${SSM_PREFIX}/${key}" \
                --value "$value" \
                --type String \
                --overwrite \
                --no-cli-pager > /dev/null 2>&1 || true
        fi
    done

    # Set webhook secret (SecureString)
    WEBHOOK_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "change-me-in-production")
    aws ssm put-parameter \
        --name "${SSM_PREFIX}/webhook_secret" \
        --value "$WEBHOOK_SECRET" \
        --type SecureString \
        --overwrite \
        --no-cli-pager > /dev/null 2>&1 || true

    echo -e "${GREEN}SSM parameters updated${NC}"
}

#==============================================================================
# Main
#==============================================================================
main() {
    echo ""
    echo -e "${BLUE}================================================${NC}"
    echo -e "${BLUE}  Mortgage Platform - Environment Setup${NC}"
    echo -e "${BLUE}================================================${NC}"
    echo ""

    check_prerequisites
    get_terraform_outputs
    generate_backend_env
    generate_frontend_env

    # Optionally update SSM parameters
    read -p "Update SSM parameters for Serverless? [y/N] " update_ssm
    if [[ "$update_ssm" =~ ^[Yy]$ ]]; then
        update_ssm_parameters
    fi

    echo ""
    echo -e "${GREEN}================================================${NC}"
    echo -e "${GREEN}  Environment Setup Complete!${NC}"
    echo -e "${GREEN}================================================${NC}"
    echo ""
    echo "Generated files:"
    echo "  - ${BACKEND_ENV_FILE}"
    echo "  - ${FRONTEND_ENV_FILE}"
    echo ""
    echo "Next steps:"
    echo "  1. Review the generated .env files"
    echo "  2. Deploy backend: make backend-deploy STAGE=${STAGE}"
    echo "  3. Update frontend VITE_API_URL with the API Gateway URL"
    echo "  4. Build frontend: make frontend-build"
    echo ""
}

main
